In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df_polls = pd.read_csv("data/president_polls.csv")
df_polls.head(10)

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,fte_grade,methodology,...,election_date,stage,nationwide_batch,ranked_choice_reallocated,ranked_choice_round,party,answer,candidate_id,candidate_name,pct
0,85834,1624,J.L. Partners,NaN,NaN,J.L. Partners,619,J.L. Partners,B/C,Live Phone/Text,...,11/5/24,general,False,False,NaN,DEM,Biden,19368,Joe Biden,41.0
1,85834,1624,J.L. Partners,NaN,NaN,J.L. Partners,619,J.L. Partners,B/C,Live Phone/Text,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,45.0
2,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,DEM,Biden,19368,Joe Biden,43.0
3,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,47.0
4,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,DEM,Harris,16661,Kamala Harris,42.0
5,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,50.0
6,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,DEM,Biden,19368,Joe Biden,34.0
7,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,39.0
8,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,IND,Kennedy,31042,Robert F. Kennedy,9.0
9,85835,294,McLaughlin,NaN,NaN,McLaughlin & Associates,203,McLaughlin & Associates,C/D,Online Panel,...,11/5/24,general,False,False,NaN,IND,West,31097,Cornel West,2.0

In [29]:
df_pop = pd.read_excel("data/PopulationReport.xlsx")
df_pop.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Name,Pop. 1990,Pop. 2000,Pop. 2010,Pop. 2020,Pop. 2022,Change 2020-22
3,United States,248790925,281424600,308745538,331449520,333287557,0.005545
4,Alabama,4040389,4447207,4779736,5024356,5074296,0.00994
5,Alaska,550043,626933,710231,733378,733583,0.00028
6,Arizona,3665339,5130247,6392017,7151507,7359197,0.029041
7,Arkansas,2350624,2673293,2915918,3011555,3045637,0.011317
8,California,29811427,33871653,37253956,39538245,39029342,-0.012871
9,Colorado,3294473,4302086,5029196,5773733,5839926,0.011465

In [30]:
header = df_pop.loc[2].to_list()
df_pop = df_pop[3:]
df_pop.columns = header
df_pop.head(10)

,Name,Pop. 1990,Pop. 2000,Pop. 2010,Pop. 2020,Pop. 2022,Change 2020-22
3,United States,248790925,281424600,308745538,331449520,333287557,0.005545
4,Alabama,4040389,4447207,4779736,5024356,5074296,0.00994
5,Alaska,550043,626933,710231,733378,733583,0.00028
6,Arizona,3665339,5130247,6392017,7151507,7359197,0.029041
7,Arkansas,2350624,2673293,2915918,3011555,3045637,0.011317
8,California,29811427,33871653,37253956,39538245,39029342,-0.012871
9,Colorado,3294473,4302086,5029196,5773733,5839926,0.011465
10,Connecticut,3287116,3405650,3574097,3605942,3626205,0.005619
11,Delaware,666168,783559,897934,989957,1018396,0.028728
12,District of Columbia,606900,572086,601723,689546,671803,-0.025731

In [59]:
df_pov = pd.read_excel("data/PovertyReport.xlsx")
df_pov.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,Percent,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,All people in poverty (2021),NaN,NaN,NaN,Children ages 0-17 in poverty (2021),NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,90% confidence interval of estimate,NaN,NaN,90% confidence interval of estimate,NaN
4,Name,NaN,NaN,NaN,Percent,NaN,Lower Bound,Upper Bound,Percent,Lower Bound,Upper Bound
5,Alabama,NaN,NaN,NaN,16.3,NaN,15.9,16.7,22.7,21.9,23.5
6,Alaska,NaN,NaN,NaN,10.8,NaN,10.3,11.3,13.5,12.7,14.3
7,Arizona,NaN,NaN,NaN,12.9,NaN,12.6,13.2,17.8,17.2,18.4
8,Arkansas,NaN,NaN,NaN,16,NaN,15.6,16.4,21.8,21,22.6
9,California,NaN,NaN,NaN,12.3,NaN,12.2,12.4,15.8,15.5,16.1

In [60]:
df_pov = df_pov[2:57]
df_pov.dropna(axis = 1, how ='all', inplace = True)
df_pov

,Unnamed: 0,Unnamed: 4,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
2,NaN,All people in poverty (2021),NaN,NaN,Children ages 0-17 in poverty (2021),NaN,NaN
3,NaN,NaN,90% confidence interval of estimate,NaN,NaN,90% confidence interval of estimate,NaN
4,Name,Percent,Lower Bound,Upper Bound,Percent,Lower Bound,Upper Bound
5,Alabama,16.3,15.9,16.7,22.7,21.9,23.5
6,Alaska,10.8,10.3,11.3,13.5,12.7,14.3
7,Arizona,12.9,12.6,13.2,17.8,17.2,18.4
8,Arkansas,16,15.6,16.4,21.8,21,22.6
9,California,12.3,12.2,12.4,15.8,15.5,16.1
10,Colorado,9.7,9.5,9.9,11.8,11.2,12.4
11,Connecticut,10.1,9.8,10.4,12.9,12.2,13.6
12,Delaware,11.5,11,12,16.2,15.3,17.1
13,District of Columbia,16.8,15.9,17.7,25.5,22.5,28.5
14,Florida,13.2,13,13.4,18.4,17.8,19
15,Georgia,14.2,13.9,14.5,20.5,19.9,21.1
16,Hawaii,10.9,10.4,11.4,12.9,12,13.8
17,Idaho,10.8,10.3,11.3,12.5,11.7,13.3
18,Illinois,12.1,11.9,12.3,15.9,15.4,16.4
19,Indiana,12.1,11.8,12.4,15.7,15.1,16.3
20,Iowa,11,10.6,11.4,12.4,11.8,13
21,Kansas,11.6,11.2,12,13.5,12.8,14.2
22,Kentucky,16.3,16,16.6,21.2,20.5,21.9
23,Louisiana,19.5,19.1,19.9,26.9,26.1,27.7
24,Maine,11.2,10.7,11.7,13.8,12.9,14.7
25,Maryland,10.3,10,10.6,14,13.4,14.6
26,Massachusetts,10.4,10.2,10.6,12.8,12.2,13.4
27,Michigan,13,12.8,13.2,17.6,17.1,18.1
28,Minnesota,9.3,9.1,9.5,10.8,10.3,11.3
29,Mississippi,19.2,18.7,19.7,27.1,26.2,28
30,Missouri,12.8,12.5,13.1,16.5,15.9,17.1
31,Montana,12,11.5,12.5,14.9,14.1,15.7
32,National,12.8,12.7,12.9,16.9,16.7,17.1
33,Nebraska,10.5,10.1,10.9,12.1,11.3,12.9
34,Nevada,14,13.6,14.4,18.8,18,19.6
35,New Hampshire,7.4,7,7.8,9.3,8.5,10.1
36,New Jersey,10.2,10,10.4,13.9,13.3,14.5
37,New Mexico,17.7,17.1,18.3,23.1,22.1,24.1
38,New York,14,13.8,14.2,18.8,18.3,19.3
39,North Carolina,13.5,13.2,13.8,18.2,17.6,18.8
40,North Dakota,10.9,10.3,11.5,11.5,10.6,12.4
41,Ohio,13.3,13.1,13.5,18.2,17.7,18.7
42,Oklahoma,15.4,15.1,15.7,20.5,19.8,21.2
43,Oregon,12.2,11.9,12.5,13.8,13.1,14.5
44,Pennsylvania,12,11.8,12.2,16.3,15.7,16.9
45,Rhode Island,12.1,11.6,12.6,17,16.1,17.9
46,South Carolina,14.5,14.2,14.8,19.7,19,20.4
47,South Dakota,11.9,11.4,12.4,14.4,13.5,15.3
48,Tennessee,13.7,13.4,14,18.4,17.8,19
49,Texas,14.2,14,14.4,19.5,19,20
50,Utah,8.7,8.3,9.1,8.5,7.9,9.1
51,Vermont,10.2,9.7,10.7,11.2,10.3,12.1
52,Virginia,10.3,10.1,10.5,13.3,12.8,13.8
53,Washington,9.9,9.7,10.1,12,11.4,12.6
54,West Virginia,16.8,16.3,17.3,21.4,20.5,22.3
55,Wisconsin,10.8,10.6,11,13.6,13.1,14.1
56,Wyoming,10.6,9.9,11.3,12.1,11.1,13.1

In [61]:
all_pov = df_pov.loc[4][1:4].to_list()
all_pov_head = ['Overall '+ head for head in all_pov]

In [62]:
youth_pov = df_pov.loc[4][4:].to_list()
youth_pov_head = ['Youth '+ head for head in all_pov]

In [63]:
all_pov_head, youth_pov_head

(['Overall Percent', 'Overall Lower Bound', 'Overall Upper Bound'],
 ['Youth Percent', 'Youth Lower Bound', 'Youth Upper Bound'])

In [86]:
pov_header = ['Name']
pov_header += all_pov_head
pov_header += youth_pov_head
df_pov = df_pov[3:]
df_pov.columns = pov_header
df_pov.head(10)

,Name,Overall Percent,Overall Lower Bound,Overall Upper Bound,Youth Percent,Youth Lower Bound,Youth Upper Bound
11,Connecticut,10.1,9.8,10.4,12.9,12.2,13.6
12,Delaware,11.5,11,12,16.2,15.3,17.1
13,District of Columbia,16.8,15.9,17.7,25.5,22.5,28.5
14,Florida,13.2,13,13.4,18.4,17.8,19
15,Georgia,14.2,13.9,14.5,20.5,19.9,21.1
16,Hawaii,10.9,10.4,11.4,12.9,12,13.8
17,Idaho,10.8,10.3,11.3,12.5,11.7,13.3
18,Illinois,12.1,11.9,12.3,15.9,15.4,16.4
19,Indiana,12.1,11.8,12.4,15.7,15.1,16.3
20,Iowa,11,10.6,11.4,12.4,11.8,13

In [96]:
df_unemp = pd.read_excel("data/UnemploymentReport.xlsx")
df_unemp.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Unemployment Rate (percent),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,FIPS,Name,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,Median Household Income (2021)
3,NaN,01000,Alabama,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,"$53,990"
4,NaN,02000,Alaska,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,"$78,437"
5,NaN,04000,Arizona,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,"$68,967"
6,NaN,05000,Arkansas,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,"$52,577"
7,NaN,06000,California,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,"$84,831"
8,NaN,08000,Colorado,5,3.7,3.1,2.6,3.0,2.7,6.8,5.4,3.0,"$82,228"
9,NaN,09000,Connecticut,6.6,5.6,4.8,4.4,3.9,3.6,7.9,6.3,4.2,"$83,628"

In [97]:
df_unemp.drop(df_unemp.columns[[0,1]], axis = 1, inplace = True)
df_unemp

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Unemployment Rate (percent),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Name,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,Median Household Income (2021)
3,Alabama,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,"$53,990"
4,Alaska,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,"$78,437"
5,Arizona,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,"$68,967"
6,Arkansas,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,"$52,577"
7,California,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,"$84,831"
8,Colorado,5,3.7,3.1,2.6,3.0,2.7,6.8,5.4,3.0,"$82,228"
9,Connecticut,6.6,5.6,4.8,4.4,3.9,3.6,7.9,6.3,4.2,"$83,628"
10,Delaware,5.6,4.8,4.5,4.5,3.7,3.6,7.5,5.5,4.5,"$71,636"
11,District of Columbia,7.7,6.9,6.2,6.1,5.7,5.5,7.9,6.8,4.7,"$91,072"
12,Florida,6.4,5.5,4.9,4.3,3.6,3.2,8.1,4.6,2.9,"$63,054"
13,Georgia,7.1,6.1,5.4,4.8,4.0,3.6,6.5,3.9,3.0,"$66,507"
14,Hawaii,4.2,3.4,2.9,2.2,2.4,2.5,11.7,6.0,3.5,"$85,547"
15,Idaho,4.4,3.9,3.7,3.2,2.9,2.9,5.5,3.5,2.7,"$66,318"
16,Illinois,7.2,6.0,5.9,4.9,4.4,4.0,9.3,6.1,4.6,"$72,215"
17,Indiana,5.9,4.8,4.4,3.5,3.4,3.3,7.3,3.9,3.0,"$62,723"
18,Iowa,4.2,3.7,3.6,3.1,2.6,2.7,5.2,3.8,2.7,"$65,645"
19,Kansas,4.5,4.2,4.0,3.6,3.4,3.3,5.8,3.3,2.7,"$64,128"
20,Kentucky,6.4,5.2,5.0,4.8,4.2,4.1,6.5,4.4,3.9,"$55,532"
21,Louisiana,6.3,6.3,6.1,5.1,4.8,4.6,8.6,5.6,3.7,"$52,090"
22,Maine,5.6,4.4,3.8,3.4,3.2,2.9,5.1,4.6,3.0,"$64,823"
23,Maryland,5.7,5.0,4.3,4.0,3.8,3.4,6.5,5.3,3.2,"$90,129"
24,Massachusetts,5.7,4.8,4.0,3.8,3.5,3.0,9.4,5.5,3.8,"$89,577"
25,Michigan,7.2,5.4,5.0,4.6,4.2,4.1,10.0,5.8,4.2,"$63,444"
26,Minnesota,4.3,3.8,3.9,3.5,3.0,3.3,6.3,3.8,2.7,"$77,712"
27,Mississippi,7.6,6.5,5.9,5.2,4.9,5.5,8.0,5.5,3.9,"$48,871"
28,Missouri,6.2,5.1,4.5,3.7,3.2,3.2,6.1,4.1,2.5,"$61,815"
29,Montana,4.7,4.3,4.3,4.1,3.7,3.5,5.8,3.4,2.6,"$63,357"
30,Nebraska,3.3,3.0,3.1,3.0,2.9,3.1,4.3,2.7,2.3,"$66,949"
31,Nevada,8.2,6.8,5.8,5.0,4.4,4.1,13.5,6.9,5.4,"$66,194"
32,New Hampshire,4.3,3.4,2.9,2.8,2.6,2.6,6.7,3.4,2.5,"$88,268"
33,New Jersey,6.7,5.7,4.9,4.5,4.0,3.5,9.4,6.6,3.7,"$89,227"
34,New Mexico,6.6,6.6,6.7,6.1,4.9,5.0,7.9,7.1,4.0,"$54,304"
35,New York,6.3,5.2,4.9,4.6,4.1,3.9,9.8,7.0,4.3,"$74,230"
36,North Carolina,6.1,5.7,5.1,4.5,4.0,3.9,7.2,4.9,3.7,"$61,997"
37,North Dakota,2.6,2.8,3.1,2.6,2.4,2.2,5.0,3.1,2.1,"$67,603"
38,Ohio,5.8,5.0,5.0,5.0,4.5,4.2,8.2,5.1,4.0,"$62,286"
39,Oklahoma,4.3,4.3,4.6,4.0,3.3,3.1,6.3,4.0,3.0,"$55,829"
40,Oregon,6.7,5.5,4.7,4.1,4.0,3.7,7.6,5.2,4.2,"$71,441"
41,Pennsylvania,5.9,5.4,5.3,5.0,4.4,4.3,8.9,6.0,4.4,"$68,931"
42,Rhode Island,7.8,6.0,5.2,4.5,4.0,3.5,9.2,5.5,3.2,"$73,324"
43,South Carolina,6.3,5.9,4.9,4.2,3.4,2.8,6.0,3.9,3.2,"$59,447"
44,South Dakota,3.3,3.0,3.0,3.1,2.8,2.8,4.2,2.6,2.1,"$66,843"
45,Tennessee,6.6,5.6,4.7,3.7,3.5,3.3,7.5,4.5,3.4,"$59,698"
46,Texas,5.2,4.5,4.6,4.3,3.9,3.5,7.7,5.6,3.9,"$66,959"
47,Utah,3.6,3.5,3.3,3.1,2.9,2.5,4.8,2.7,2.3,"$79,449"
48,Vermont,4,3.5,3.1,3.0,2.5,2.1,5.7,3.7,2.6,"$72,415"
49,Virginia,5.1,4.4,4.0,3.7,3.0,2.8,6.5,3.9,2.9,"$80,926"
50,Washington,5.9,5.4,5.2,4.6,4.4,4.2,8.5,5.2,4.2,"$84,155"
51,West Virginia,6.5,6.6,6.1,5.2,5.1,5.0,8.2,5.1,3.9,"$51,122"
52,Wisconsin,5.3,4.4,3.9,3.3,3.0,3.2,6.4,3.8,2.9,"$67,150"
53,Wyoming,4.3,4.2,5.4,4.3,4.1,3.7,5.9,4.6,3.6,"$66,508"
54,Puerto Rico,13.9,12.0,11.8,10.8,9.2,8.3,NaN,7.9,6.0,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
from numbers import Number
unemp_header = []
for x in df_unemp.loc[2].to_list(): 
    if isinstance(x, Number) == True:
        x = int(x)
        temp = 'Unemployemt pct ' + str(x)
        unemp_header.append(temp)
    else:
        unemp_header.append(x)

In [99]:
df_unemp = df_unemp[3:54]
df_unemp.columns = unemp_header
df_unemp

,Name,2014,Unemployemt pct 2015,Unemployemt pct 2016,Unemployemt pct 2017,Unemployemt pct 2018,Unemployemt pct 2019,Unemployemt pct 2020,Unemployemt pct 2021,Unemployemt pct 2022,Median Household Income (2021)
3,Alabama,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,"$53,990"
4,Alaska,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,"$78,437"
5,Arizona,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,"$68,967"
6,Arkansas,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,"$52,577"
7,California,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,"$84,831"
8,Colorado,5,3.7,3.1,2.6,3.0,2.7,6.8,5.4,3.0,"$82,228"
9,Connecticut,6.6,5.6,4.8,4.4,3.9,3.6,7.9,6.3,4.2,"$83,628"
10,Delaware,5.6,4.8,4.5,4.5,3.7,3.6,7.5,5.5,4.5,"$71,636"
11,District of Columbia,7.7,6.9,6.2,6.1,5.7,5.5,7.9,6.8,4.7,"$91,072"
12,Florida,6.4,5.5,4.9,4.3,3.6,3.2,8.1,4.6,2.9,"$63,054"
13,Georgia,7.1,6.1,5.4,4.8,4.0,3.6,6.5,3.9,3.0,"$66,507"
14,Hawaii,4.2,3.4,2.9,2.2,2.4,2.5,11.7,6.0,3.5,"$85,547"
15,Idaho,4.4,3.9,3.7,3.2,2.9,2.9,5.5,3.5,2.7,"$66,318"
16,Illinois,7.2,6.0,5.9,4.9,4.4,4.0,9.3,6.1,4.6,"$72,215"
17,Indiana,5.9,4.8,4.4,3.5,3.4,3.3,7.3,3.9,3.0,"$62,723"
18,Iowa,4.2,3.7,3.6,3.1,2.6,2.7,5.2,3.8,2.7,"$65,645"
19,Kansas,4.5,4.2,4.0,3.6,3.4,3.3,5.8,3.3,2.7,"$64,128"
20,Kentucky,6.4,5.2,5.0,4.8,4.2,4.1,6.5,4.4,3.9,"$55,532"
21,Louisiana,6.3,6.3,6.1,5.1,4.8,4.6,8.6,5.6,3.7,"$52,090"
22,Maine,5.6,4.4,3.8,3.4,3.2,2.9,5.1,4.6,3.0,"$64,823"
23,Maryland,5.7,5.0,4.3,4.0,3.8,3.4,6.5,5.3,3.2,"$90,129"
24,Massachusetts,5.7,4.8,4.0,3.8,3.5,3.0,9.4,5.5,3.8,"$89,577"
25,Michigan,7.2,5.4,5.0,4.6,4.2,4.1,10.0,5.8,4.2,"$63,444"
26,Minnesota,4.3,3.8,3.9,3.5,3.0,3.3,6.3,3.8,2.7,"$77,712"
27,Mississippi,7.6,6.5,5.9,5.2,4.9,5.5,8.0,5.5,3.9,"$48,871"
28,Missouri,6.2,5.1,4.5,3.7,3.2,3.2,6.1,4.1,2.5,"$61,815"
29,Montana,4.7,4.3,4.3,4.1,3.7,3.5,5.8,3.4,2.6,"$63,357"
30,Nebraska,3.3,3.0,3.1,3.0,2.9,3.1,4.3,2.7,2.3,"$66,949"
31,Nevada,8.2,6.8,5.8,5.0,4.4,4.1,13.5,6.9,5.4,"$66,194"
32,New Hampshire,4.3,3.4,2.9,2.8,2.6,2.6,6.7,3.4,2.5,"$88,268"
33,New Jersey,6.7,5.7,4.9,4.5,4.0,3.5,9.4,6.6,3.7,"$89,227"
34,New Mexico,6.6,6.6,6.7,6.1,4.9,5.0,7.9,7.1,4.0,"$54,304"
35,New York,6.3,5.2,4.9,4.6,4.1,3.9,9.8,7.0,4.3,"$74,230"
36,North Carolina,6.1,5.7,5.1,4.5,4.0,3.9,7.2,4.9,3.7,"$61,997"
37,North Dakota,2.6,2.8,3.1,2.6,2.4,2.2,5.0,3.1,2.1,"$67,603"
38,Ohio,5.8,5.0,5.0,5.0,4.5,4.2,8.2,5.1,4.0,"$62,286"
39,Oklahoma,4.3,4.3,4.6,4.0,3.3,3.1,6.3,4.0,3.0,"$55,829"
40,Oregon,6.7,5.5,4.7,4.1,4.0,3.7,7.6,5.2,4.2,"$71,441"
41,Pennsylvania,5.9,5.4,5.3,5.0,4.4,4.3,8.9,6.0,4.4,"$68,931"
42,Rhode Island,7.8,6.0,5.2,4.5,4.0,3.5,9.2,5.5,3.2,"$73,324"
43,South Carolina,6.3,5.9,4.9,4.2,3.4,2.8,6.0,3.9,3.2,"$59,447"
44,South Dakota,3.3,3.0,3.0,3.1,2.8,2.8,4.2,2.6,2.1,"$66,843"
45,Tennessee,6.6,5.6,4.7,3.7,3.5,3.3,7.5,4.5,3.4,"$59,698"
46,Texas,5.2,4.5,4.6,4.3,3.9,3.5,7.7,5.6,3.9,"$66,959"
47,Utah,3.6,3.5,3.3,3.1,2.9,2.5,4.8,2.7,2.3,"$79,449"
48,Vermont,4,3.5,3.1,3.0,2.5,2.1,5.7,3.7,2.6,"$72,415"
49,Virginia,5.1,4.4,4.0,3.7,3.0,2.8,6.5,3.9,2.9,"$80,926"
50,Washington,5.9,5.4,5.2,4.6,4.4,4.2,8.5,5.2,4.2,"$84,155"
51,West Virginia,6.5,6.6,6.1,5.2,5.1,5.0,8.2,5.1,3.9,"$51,122"
52,Wisconsin,5.3,4.4,3.9,3.3,3.0,3.2,6.4,3.8,2.9,"$67,150"
53,Wyoming,4.3,4.2,5.4,4.3,4.1,3.7,5.9,4.6,3.6,"$66,508"

In [100]:
df_edu = pd.read_excel("data/EducationReport.xlsx")
df_edu

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,NaN,NaN,NaN,NaN,NaN,Urban,NaN,NaN,...,NaN,NaN,NaN,NaN,Rural,NaN,NaN,NaN,NaN,NaN
2,Name,1970,1980.000000,1990.000000,2000.000000,2008-2012,2017-2021,1970,1980.000000,1990.000000,...,2008-2012,2017-2021,NaN,NaN,1970,1980.000000,1990.000000,2000.000000,2008-2012,2017-2021
3,United States,0.106618,0.162294,0.203377,0.244016,0.28485,0.3367,0.115345,0.174818,0.219365,...,0.304509,0.357413,NaN,NaN,0.067304,0.105002,0.122850,0.149004,0.175907,0.210755
4,Alabama,0.07847,0.121797,0.156808,0.190347,0.222649,0.266689,0.088839,0.137495,0.178450,...,0.251577,0.298204,NaN,NaN,0.052999,0.082044,0.097791,0.115997,0.135258,0.162359
5,Alaska,0.141403,0.210760,0.230335,0.247149,0.274762,0.305938,0.157216,0.228411,0.254952,...,0.2976,0.331677,NaN,NaN,0.119009,0.182162,0.188628,0.206540,0.229046,0.253722
6,Arizona,0.125604,0.174137,0.202884,0.235310,0.266293,0.312065,0.129671,0.179187,0.209834,...,0.273252,0.319221,NaN,NaN,0.074745,0.103254,0.097785,0.124178,0.140198,0.166593
7,Arkansas,0.066551,0.108201,0.133211,0.166606,0.197983,0.243047,0.082484,0.132572,0.163141,...,0.238732,0.290503,NaN,NaN,0.050975,0.082526,0.098276,0.121767,0.138764,0.164596
8,California,0.134449,0.196017,0.233568,0.266209,0.304534,0.352704,0.135546,0.197328,0.235599,...,0.306828,0.355309,NaN,NaN,0.086878,0.145792,0.156152,0.179830,0.213928,0.243258
9,Colorado,0.14926,0.229590,0.269690,0.326927,0.366763,0.428283,0.161532,0.240337,0.281970,...,0.380142,0.441904,NaN,NaN,0.091462,0.172372,0.197881,0.250248,0.286404,0.336682
10,Connecticut,0.13663,0.206595,0.271807,0.314074,0.361566,0.405531,0.137507,0.207711,0.273050,...,0.363649,0.408065,NaN,NaN,0.119546,0.186152,0.249992,0.274655,0.326343,0.36185
11,Delaware,0.130935,0.174684,0.214054,0.250491,0.285223,0.336473,0.130935,0.174684,0.214054,...,0.285223,0.336473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,District of Columbia,0.177834,0.274620,0.333108,0.390698,0.512057,0.614011,0.177834,0.274620,0.333108,...,0.512057,0.614011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Florida,0.10264,0.148818,0.182781,0.223348,0.261675,0.315321,0.104573,0.151487,0.185921,...,0.266742,0.320737,NaN,NaN,0.06223,0.089220,0.107579,0.117666,0.130996,0.159056
14,Georgia,0.092111,0.145929,0.193159,0.242998,0.27764,0.330027,0.105842,0.164936,0.217833,...,0.307398,0.361352,NaN,NaN,0.052747,0.085326,0.101283,0.124666,0.147459,0.178841
15,Hawaii,0.13966,0.203458,0.228824,0.261741,0.296069,0.343405,0.149638,0.211661,0.238140,...,0.305767,0.353383,NaN,NaN,0.074338,0.153199,0.178103,0.213399,0.254185,0.301383
16,Idaho,0.099612,0.158279,0.176512,0.216653,0.247128,0.291329,0.111467,0.172487,0.193827,...,0.269949,0.3153,NaN,NaN,0.08588,0.139576,0.151373,0.180493,0.203571,0.240958
17,Illinois,0.103103,0.162049,0.210448,0.260614,0.310799,0.361622,0.110394,0.173585,0.226415,...,0.331704,0.383797,NaN,NaN,0.060661,0.094905,0.110456,0.134726,0.163243,0.193047
18,Indiana,0.083263,0.125197,0.155594,0.194081,0.229836,0.278436,0.092169,0.138557,0.174380,...,0.255567,0.306862,NaN,NaN,0.058063,0.086981,0.099628,0.120018,0.145082,0.178201
19,Iowa,0.090952,0.139436,0.168501,0.212089,0.253246,0.297054,0.116557,0.174553,0.211323,...,0.31096,0.354836,NaN,NaN,0.069001,0.106662,0.124631,0.155141,0.180039,0.214614
20,Kansas,0.113769,0.170324,0.210977,0.258039,0.299973,0.344044,0.136973,0.204539,0.254084,...,0.351355,0.396098,NaN,NaN,0.08647,0.126048,0.145107,0.175845,0.200162,0.231077
21,Kentucky,0.072108,0.110768,0.136311,0.171353,0.209809,0.2571,0.08902,0.138369,0.173612,...,0.263182,0.315569,NaN,NaN,0.051588,0.078694,0.090820,0.113470,0.139137,0.174089
22,Louisiana,0.090497,0.139043,0.161263,0.187276,0.214235,0.255303,0.097415,0.149704,0.173926,...,0.230186,0.273793,NaN,NaN,0.062918,0.093206,0.102729,0.119143,0.136357,0.155011
23,Maine,0.083635,0.143968,0.187719,0.228718,0.273235,0.336164,0.092904,0.153931,0.209669,...,0.306117,0.375803,NaN,NaN,0.072556,0.131796,0.159578,0.194413,0.228513,0.278814
24,Maryland,0.139367,0.203552,0.264570,0.314499,0.363411,0.415602,0.14171,0.206442,0.268166,...,0.367327,0.419116,NaN,NaN,0.065199,0.111101,0.143405,0.176237,0.226792,0.283305
25,Massachusetts,0.125529,0.200283,0.272322,0.331899,0.389724,0.452052,0.125757,0.200338,0.272515,...,0.390327,0.452619,NaN,NaN,0.107855,0.196505,0.259557,0.315436,0.352596,0.417738
26,Michigan,0.094225,0.142593,0.173560,0.217623,0.255252,0.306171,0.099029,0.149687,0.184564,...,0.272816,0.325442,NaN,NaN,0.067696,0.108001,0.121805,0.151185,0.180221,0.221142
27,Minnesota,0.111001,0.173629,0.218217,0.274332,0.322345,0.375689,0.130587,0.201201,0.250543,...,0.361563,0.416791,NaN,NaN,0.066735,0.107781,0.128062,0.164147,0.198181,0.233614
28,Mississippi,0.080558,0.122889,0.147464,0.169040,0.199743,0.232474,0.101692,0.152309,0.183556,...,0.242136,0.277236,NaN,NaN,0.06955,0.105127,0.123064,0.141232,0.165323,0.192649
29,Missouri,0.089716,0.138939,0.177957,0.215817,0.257719,0.30689,0.101456,0.159302,0.205492,...,0.296115,0.347473,NaN,NaN,0.057928,0.085794,0.101666,0.125161,0.150022,0.182961
30,Montana,0.11011,0.174659,0.197934,0.243702,0.284829,0.336556,0.140851,0.199977,0.222439,...,0.305297,0.355043,NaN,NaN,0.095169,0.161338,0.184879,0.230535,0.273938,0.326785
31,Nebraska,0.096496,0.155174,0.189410,0.237427,0.281114,0.329468,0.126506,0.193396,0.233694,...,0.333306,0.38133,NaN,NaN,0.067138,0.113695,0.133520,0.168992,0.196278,0.232774
32,Nevada,0.107858,0.144385,0.152779,0.181560,0.222168,0.260594,0.112885,0.148155,0.156346,...,0.228875,0.268924,NaN,NaN,0.081746,0.120912,0.129140,0.147739,0.16332,0.18351
33,New Hampshire,0.108512,0.182090,0.243651,0.286539,0.334352,0.382347,0.110433,0.185870,0.255420,...,0.35179,0.404387,NaN,NaN,0.105911,0.176642,0.224882,0.262082,0.306422,0.345875
34,New Jersey,0.118357,0.183391,0.248540,0.297794,0.353814,0.415006,0.118357,0.183391,0.248540,...,0.353814,0.415006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,New Mexico,0.127343,0.175840,0.204138,0.234534,0.256295,0.285315,0.149798,0.203726,0.240034,...,0.290065,0.325466,NaN,NaN,0.101009,0.134531,0.146045,0.172427,0.188694,0.202488
36,New York,0.118878,0.179418,0.231316,0.273726,0.327882,0.381129,0.121536,0.184248,0.238581,...,0.338198,0.391501,NaN,NaN,0.08313,0.120479,0.142767,0.165600,0.198305,0.240156
37,North Carolina,0.084506,0.132352,0.173751,0.224629,0.268282,0.330163,0.095807,0.149215,0.196011,...,0.29873,0.361826,NaN,NaN,0.057567,0.090991,0.113094,0.142697,0.169979,0.213229
38,North Dakota,0.083879,0.148222,0.180656,0.219888,0.270558,0.310881,0.130289,0.208453,0.244681,...,0.337893,0.379427,NaN,NaN,0.063564,0.115953,0.139090,0.172777,0.210441,0.242522
39,Ohio,0.092659,0.136524,0.169729,0.210953,0.247339,0.296916,0.100502,0.148196,0.186759,...,0.272907,0.324835,NaN,NaN,0.060674,0.091831,0.104115,0.125543,0.149893,0.18499
40,Oklahoma,0.100202,0.150733,0.177892,0.202785,0.232332,0.268486,0.114543,0.170608,0.200169,...,0.259951,0.299398,NaN,NaN,0.082358,0.123541,0.143425,0.163488,0.183106,0.206484
41,Oregon,0.117793,0.178522,0.205981,0.250807,0.292457,0.350372,0.128228,0.193708,0.223423,...,0.31581,0.377196,NaN,NaN,0.081075,0.121893,0.135461,0.160086,0.182828,0.215328
42,Pennsylvania,0.087488,0.135550,0.179443,0.223514,0.27046,0.331148,0.091963,0.142745,0.189953,...,0.286267,0.349223,NaN,NaN,0.055278,0.086025,0.105035,0.128897,0.156744,0.190644
43,Rhode Island,0.093877,0.154314,0.212700,0.256009,0.307637,0.353201,0.093877,0.154314,0.212700,...,0.307637,0.353201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,South Carolina,0.089668,0.134233,0.166467,0.204181,0.245569,0.298367,0.09571,0.143381,0.178903,...,0.262836,0.316933,NaN,NaN,0.068426,0.099448,0.113818,0.138882,0.159169,0.190094
45,South Dakota,0.085961,0.140065,0.171640,0.215052,0.260493,0.299942,0.095161,0.158375,0.196986,...,0.288703,0.337634,NaN,NaN,0.081789,0.130069,0.155280,0.192694,0.23576,0.261976
46,Tennessee,0.078941,0.125981,0.159599,0.195648,0.234933,0.290372,0.090787,0.144003,0.183095,...,0.265699,0.326088,NaN,NaN,0.045025,0.073821,0.088216,0.109508,0.137691,0.169286
47,Texas,0.108726,0.168801,0.203180,0.232376,0.262594,0.315326,0.118918,0.183754,0.219553,...,0.278241,0.3315,NaN,NaN,0.069306,0.101644,0.115448,0.134691,0.153107,0.181662
48,Utah,0.139799,0.198785,0.222610,0.261261,0.298569,0.354271,0.146392,0.207001,0.230849,...,0.305924,0.361817,NaN,NaN,0.093754,0.141019,0.159083,0.209419,0.240731,0.29096
49,Vermont,0.114876,0.190421,0.243122,0.294454,0.342054,0.408592,0.143708,0.221337,0.290466,...,0.400601,0.475208,NaN,NaN,0.103862,0.178225,0.222710,0.269753,0.314243,0.375268
50,Virginia,0.123031,0.190901,0.244765,0.294646,0.346785,0.403296,0.141119,0.217266,0.274261,...,0.379022,0.434768,NaN,NaN,0.052119,0.081079,0.097061,0.123816,0.151778,0.188677
51,Washington,0.127221,0.189520,0.229328,0.277315,0.315722,0.372824,0.130693,0.195115,0.237262,...,0.326279,0.384697,NaN,NaN,0.100632,0.147017,0.164028,0.198132,0.226444,0.265992
52,West Virginia,0.067709,0.104171,0.123333,0.148316,0.179078,0.217762,0.077192,0.118776,0.143317,...,0.205215,0.249637,NaN,NaN,0.054476,0.083728,0.094655,0.115334,0.139185,0.166335
53,Wisconsin,0.097581,0.148251,0.177418,0.224195,0.263983,0.314895,0.10887,0.163976,0.197622,...,0.293096,0.347737,NaN,NaN,0.067285,0.107948,0.124164,0.156313,0.186877,0.225089
54,Wyoming,0.117809,0.171535,0.187908,0.219101,0.242608,0.285223,0.131783,0.187194,0.205376,...,0.231703,0.27858,NaN,NaN,0.111255,0.164637,0.180311,0.219061,0.247243,0.288242
55,Puerto Rico,NaN,NaN,NaN,0.182777,0.224841,0.274314,NaN,NaN,NaN,...,0.227474,0.277453,NaN,NaN,NaN,NaN,NaN,0.122238,0.163348,0.201467
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,"For 1970 and 1980, the share of adults who are...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN